### ISSUE TITLE
Cookies "secure" flag: AntiforgeryOptions.RequiresSsl and HttpRequest.IsSecure

### ISSUE THREAD

**Issue by luisgoncalves** [aspnet/Antiforgery#114]
On the [`DefaultAntiforgeryTokenStore`](https://github.com/aspnet/Antiforgery/blob/rel/1.1.0/src/Microsoft.AspNetCore.Antiforgery/Internal/DefaultAntiforgeryTokenStore.cs#L77) the `AntiforgeryOptions.RequiresSsl` flag is used to configure the "secure" flag of the resulting cookie. If `AntiforgeryOptions.RequiresSsl` is true, than the "secure" flag is enforced. 

However, if `AntiforgeryOptions.RequiresSsl` is false, **nothing is done** on the "secure" flag. The source code contains a comment stating that the _"secure" flag is populated out of band_. Where's this "out of band" place exactly? Shouldn't the "secure" flag be set accordingly to `HttpRequest.IsHttps`, similar to how it is done on other components?

**Comment by Eilon** [comment]
I believe the code is correct: if `RequireSsl` is true, *then the cookie will work only on SSL connections*. Otherwise, the cookie may be transmitted on non-SSL or SSL connections.

As to the comment, that's a mystery. It might be a reference to the [`CookiePolicyMiddleware`](https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.CookiePolicy/CookiePolicyMiddleware.cs), but looking at that code, it doesn't matter what you set on the cookie, the middleware will successfully do its thing. And the `Secure` property on the cookie is just a plain old `bool` so it has no concept of "not set" or "null." I'm guessing the comment is super old and based on some older designs. I'm having a hard time following the history far enough back to actually decipher this, though, so I'll leave that as my conclusion.

**Comment by luisgoncalves** [comment]
> Otherwise, the cookie may be transmitted on non-SSL or SSL connections.

In a scenario where a page is served over SSL but `RequiresSsl` is false, the anti-forgery cookie may be leaked through a subsequent request to a non-SSL endpoint. 

I was just wondering if the value of the `Secure` flag should be set to the value of `HttpRequest.IsHttps` in this case.... A page served over SSL wouldn't be able to POST to non-SSL XSRF-protected endpoints, but that seems a weird scenario. It just seemed more protective for an application that might have both SSL and non-SSL endpoints.

I just wanted to raise the question for your consideration. Feel free to close this now that you've analysed it. Nevertheless, `RequiresSsl` and the `CookiePolicyMiddleware` options probably give enough flexibility for mixed scenarios.

**Comment by Eilon** [comment]
Yeah I see what you're getting at. It might make sense to follow the pattern we have elsewhere with the [`CookieSecurePolicy`](https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http.Abstractions/CookieSecurePolicy.cs) enum, which has more precise and flexible behavior. I'm guessing when we added `CookieSecurePolicy` we didn't look to see everywhere it ought to be applied and missed antiforgery.

We already use it here:
* Session state: https://github.com/aspnet/Session/blob/e77d7801adfec9794724e6b74c11b7afbd865e47/src/Microsoft.AspNetCore.Session/SessionOptions.cs#L42
* Cookie auth: https://github.com/aspnet/Security/blob/22d2fe99c6fd9806b36025399a217a3a8b4e50f4/src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationOptions.cs#L78

So, unless there's a good reason not to, it would seem reasonable to add this support to antiforgery cookies as well.

@rynowak @blowdart thoughts on using the `CookieSecurePolicy` enum for antiforgery cookies? Right now it's just a `bool RequireSsl` property, which isn't quite granular, and doesn't have what is likely the most desirable option, which is `SameAsRequest`.

**Comment by Eilon** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
