### ISSUE TITLE
Clean up antiforgery samples

### ISSUE THREAD

**Issue by danroth27** [aspnet/Antiforgery#119]
Guidance from @blowdart is to not use the angular double cookie support, but instead follow the pattern used in https://github.com/aspnet/Entropy/tree/dev/samples/Mvc.AjaxAntiforgeryAuth.Web.

**Comment by Eilon** [comment]
We should:

1. Move the sample in this repo to Entropy and rename to `samples/Antiforgery.Angular1` (note the `1` at the end, as opposed to Angular 2)
2. Rename the sample that's already in Entropy from `Mvc.AjaxAntiforgeryAuth.Web` to `Antiforgery.MvcWithAuthAndAjax`
3. Delete the now-empty `samples/` folder of this repo
4. Update the README.md file of this repo to point to the two samples in Entropy (with a brief sentence explaining what each sample is). Make sure the MVC sample is listed first (because it is more canonical).

**Comment by rynowak** [comment]
IIRC the reason why the entropy sample isn't here already is due to dependencies.

**Comment by Eilon** [comment]
@rynowak correct. Our goal is to have the antiforgery samples near each other, which unfortunately means they can't live here.
