### ISSUE TITLE
Remove Antiforgery field from model before being handled by MVC

### ISSUE THREAD

**Issue by stephtr** [aspnet/Antiforgery#160]
When using an `IDictionary` as model in MVC, for example like:
```
[HttpPost]
public IActionResult Index(IDictionary<string, string> viewData)
```
`viewData` contains the `__RequestVerificationToken` field. This is particularly impractical if one instead uses an `IDictionary<int, int>`, which then produces a middleware exception.
I know that it is possible to wrap the `IDictionary` in a class, but wouldn't it be more useful to automatically remove the field before it reaches the controller’s action?

**Comment by Eilon** [comment]
This is very odd to me... I wouldn't have expected an action method parameter such as `IDictionary<string, string> viewData` to bind anything at all because there's nothing posted named `ViewData`.

@rynowak - any idea on this? How would anything at all show up in that dictionary?

@stephtr - or, I don't suppose you have some custom model binder or formatter in operation here, do you? Something that reads headers or form fields?

**Comment by stephtr** [comment]
I reduced the code to a new mvc app (`dotnet new mvc`) with two additions:
```
        public IActionResult Test()
        {
            var model = new Dictionary<string, string>();
            model.Add("test", "abc");
            return View(model);
        }

        [HttpPost]
        public IActionResult Test(IDictionary<string, string> parameters)
        {
            return View(parameters);
        }
```

``

**Comment by Eilon** [comment]
@kichalla can you investigate?

**Comment by stephtr** [comment]
Just for information: I have additionally opened an [issue at Mvc](https://github.com/aspnet/Mvc/issues/6744).

**Comment by Eilon** [comment]
I looked into this, and this specific aspect is by design - the antiforgery middleware shouldn't be "hiding" its post data from other middleware components.

**Comment by stephtr** [comment]
Thanks for looking into it!
