### ISSUE TITLE
Antiforgery for AJAX calls

### ISSUE THREAD

**Issue by iaguilera** [aspnet/Antiforgery#17]
It would be nice that ValidateAntiForgeryTokenAttribute (or DefaultAntiforgeryTokenStore) search token in headers too, not only in values posteds from forms.

So we can easily apply CSRF protection in Ajax calls to REST services (angularjs or jquery apps).

**Comment by dibiancoj** [comment]
+1 for the concept. Or make it configurable in startup.

       pubic enum TokenStoreLocationEnum
       {
        Form
        Header
       }

----------------------------------------------------
            
            services.ConfigureAntiforgery(options =>
            {
                  options.TokenStoreLocation= TokenStoreLocationEnum.Header
             });

Something like this?

**Comment by iaguilera** [comment]
Yes it looks good :-)... Like the possibility of enable both at the same time maybe we have mvc controllers (forms) and web api controllers (header) in the same project...

**Comment by dibiancoj** [comment]
Then the attribute [ValidateAntiForgeryToken] would look in either the form, header, or both depending what is configured. If the framework can write 10 lines so 200,000 developers won't have to that would great.

**Comment by kichalla** [comment]
I think we should at least make the `GetRequestTokensAsync` method virtual?
https://github.com/aspnet/Antiforgery/blob/dev/src/Microsoft.AspNet.Antiforgery/DefaultAntiforgeryTokenStore.cs#L61

**Comment by danroth27** [comment]
@blowdart

**Comment by blowdart** [comment]
So from a security perspective the "most correct" approach is to use a non-persistent authentication mechanism when making ajax calls, as that is not vulnerable to CSRF.

However I realise not everyone wants to write a token exchange and refresh mechanism.

So being pragmatic it's a workable idea, however I don't like the idea of a global configuration. 

To my mind it ought to be configured at the point where it varies from the normal approach, [ValidateAntiForgeryToken(Location = Header, HeaderName = "X-I-Dont-Want-To-Go-OAuth")]

Alternatively we check only headers for XML/Ajax requests and only form fields for an HTTP POST, but allow you to configure which header will hold the normally form based portion.

A helper which returns the normally form based value would then be useful, but we can't have something generic enough to attach it, because, well, everyone uses whatever javascript framework is the de jour selection, and keeping up would be a nightmare.

**Comment by borgdylan** [comment]
I have already done this in a way that works well with angular. I set up an MVC endpoint that creates the required cookie (which angular reads and posts as a header in all further requests). I also did an authorization filter that validates the header. If a better way could be found that doesn't require me to JSONify and base64 encode the AntiForgery token set I'd be happier.

**Comment by sstublic** [comment]
I've just encountered this same issue and am looking into making IAntiforgeryTokenStore with one small change: if either content-type is not form or token field is not found in the form, check for header with the same name (maybe prefixed? I don't like the 'X' variant). Only if there is no token in either of these throw an exception.

It's up to the client-side code how to put the token into header for AJAX requests. I already made taghelper and angular directive for this and it's trivial.

Maybe this approach would be acceptable? It doesn't require additional configuration and is in line with convention based design.

**Comment by rynowak** [comment]
Pulling this out of the backlog.

Our rough plan here is to support falling back from form to header in the case of a form-post, or just looking at the header in the case of a non-form-post.

Since angular and other clients have this support built in, the hope is that we'll play together nicely.

**Comment by borgdylan** [comment]
:+1:

**Comment by iaguilera** [comment]
nice!

**Comment by rynowak** [comment]
3280ff6ac55aee20953fbcb7284dcdcb93aa07dd
