### ISSUE TITLE
Make HTTP method configurable

### ISSUE THREAD

**Issue by jchannon** [aspnet/Antiforgery#172]
Currently Antiforgery returns true when validating a request if the method is:

"GET"
"HEAD"
"OPTIONS"
"TRACE"

Would you be open to making these configurable in that if a user wants GET requests to be validated they can set that in the options?

**Comment by rynowak** [comment]
I think it's a reasonably request for us to make this customizable. I'm curious though, why do you want to validate `GET`?

We generally don't care about validating `GET` because if you're doing state changes on a `GET` the you've already got problems.

**Comment by jchannon** [comment]
I've just thought it through and I'm not sure it will help me in what I was
thinking of using it for.

We've had a "security team" say that you can log into the app, copy the
cookie value, logout then use that cookie value to initiate a curl request
and get data to be a problem.  Me pointing out that with https turned on
the only way you can get that cookie is if you are sat at the users desk or
compromised their machine and at that point have much bigger issues is
completely lost on them and so now I have to add state lookups per request
to satisfy their flawed pent test.

I was thinking that doing a check on GET requests might help me but it
won't.

**Comment by rynowak** [comment]
The antiforgery library is a mitigation against **CS**RF attacks - which emphasis on the **CS** which stands for **cross-site**. It is meant to protect your users from **another site** getting their client to send a post to your site and modify data using their credentials. It's not general purpose access control.

@blowdart @Tratcher  do you care to respond to this comment:
> We've had a "security team" say that you can log into the app, copy the cookie value, logout then use that cookie value to initiate a curl request and get data to be a problem

Generally yes, if you can get a users authN cookie, then you can do anything you want as that user. You could also work around CSRF easily. 

> I have to add state lookups per request to satisfy their flawed pent test.

If a malicious person has your authN cookie they could work around that as well.

**Comment by jchannon** [comment]
Yup understand. Shame I have to put in place something that adds no
security value and slows my app down for the sake of ticking a box

**Comment by blowdart** [comment]
You know your security team sucks :)

You could take the approach identity does, embed a guid in your auth cookie, and keep the corresponding value against the user. Then when the user logs out you change the guid, and check the value in the cookie on every request, but yea, it's going to be slow. 

Honestly I'd push back against your security team as you have done (no surprises there) and point out if they're running malware on a device you have bigger problems than logging into your app, but I am guessing this is an external team from a consultancy, and of course, management, because they're paying them, will believe them first.

If you want, I could email you my "official" thoughts to use as evidence :)
