### ISSUE TITLE
Add optional token expiry

### ISSUE THREAD

**Issue by blowdart** [aspnet/Antiforgery#36]
Office would like this. You can do it by using a time limited data protection payload.

https://docs.asp.net/en/latest/security/data-protection/consumer-apis/limited-lifetime-payloads.html

**Comment by Eilon** [comment]
Moving to backlog.

**Comment by GuardRex** [comment]
ok -- a **real** question now.

I took at look at the link @blowdart provided and started to hack up something that will tide me over until this issue comes off the backlog.
```c#
// _protector <-- DI'ed into the ctor from IDataProtectionProvider
var newProtector = _protector.CreateProtector("TimeLimitedProtector");
var timeLimitedProtector = newProtector.ToTimeLimitedDataProtector();
```
... with `Microsoft.AspNetCore.DataProtection.Extensions` and so far, so good.

The example shows protecting some data with ...
```c#
string protectedData = timeLimitedProtector.Protect(input, lifetime: TimeSpan.FromSeconds(5));
```
So you're suggesting that I need to replace `public string Serialize(AntiforgeryToken token) {}` in `DefaultAntiforgeryTokenSerializer` and use my `timeLimitedProtector` for ...
```c#
var bytes = _cryptoSystem.Protect(stream.ToArray());
```
yielding something like ...
```c#
var bytes = timeLimitedProtector.Protect(stream.ToArray(), lifetime: TimeSpan.FromMinutes(X));
```
? is that heading in the right direction ?

**Comment by GuardRex** [comment]
... or is it just this ...

A field to get a pool ...
```c#
private readonly ObjectPool<AntiforgerySerializationContext> _pool = 
    new DefaultObjectPoolProvider().Create(new AntiforgerySerializationContextPooledObjectPolicy());
```
Do it ...
```c#
DefaultAntiforgeryTokenSerializer theSerializer = 
    new DefaultAntiforgeryTokenSerializer(timeLimitedProtector, _pool);
string cookieValue = theSerializer.Serialize(token);
```

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2421
